#!/usr/bin/env node
// poc-builder — Phase 2 deterministic builder.
//
// Generates the DS-001 POC page (apps/poc/) purely from the synced design
// tokens and the one registered Figma component: Button/Primary (1:5) in
// Studio 810 — DS-001 Foundation. That component is a single component with a
// Label text property — no variants — so this page renders exactly one button.
// Variants are TBD; when they land in Figma they land here, not before.
//
// Deterministic on purpose: same tokens in → byte-identical output out,
// regardless of trigger source. Every color and dimension is emitted once as a
// CSS custom property taken verbatim from design/tokens/studio810/tokens.json, so
// the output cannot pass the drift gate unless the tokens themselves did. The
// page may only use what the Figma file actually publishes — eight variables
// today. A value the foundation does not publish is a design-system gap, not a
// number to invent here.
//
// Env:
//   RUN_ID       — when set, writes pipeline/runs/$RUN_ID/50-build-report.json
//   DRIFT_INJECT — "1" injects one deliberate raw color so the gate can prove
//                  it blocks drifted builds (Phase 2 negative test)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

const ROOT = new URL('../..', import.meta.url).pathname;
const OUT = join(ROOT, 'apps/poc');
const DRIFT = process.env.DRIFT_INJECT === '1';

const studio810 = JSON.parse(
  readFileSync(join(ROOT, 'design/tokens/studio810/tokens.json'), 'utf8')
).studio810;

const cssVars = [];
const tokensUsed = [];
(function walk(node, path) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('_')) continue;
    const p = path ? `${path}.${key}` : key;
    if (value && typeof value === 'object' && 'value' in value) {
      tokensUsed.push(`studio810.${p}`);
      if (typeof value.figmaName === 'string' && value.figmaName.startsWith('--')) {
        const v = value.type === 'fontFamily' ? `'${value.value}'` : value.value;
        cssVars.push(`  ${value.figmaName}: ${v};`);
      }
    } else if (value && typeof value === 'object') {
      walk(value, p);
    }
  }
})(studio810, '');
cssVars.sort();
tokensUsed.sort();

const css = `/* Generated by tools/poc-builder from design/tokens/studio810/tokens.json.
 * Do not edit by hand — regenerate instead. Every value below resolves to a
 * published Figma variable (docs/drift-gate.md). */

:root {
${cssVars.join('\n')}
}

* { box-sizing: border-box; margin: 0; }

body {
  font-family: var(--type-family), system-ui, sans-serif;
  font-size: var(--type-size-label);
  font-weight: var(--type-weight-label);
  color: var(--color-primary);
  padding: var(--space-control-x);
}

.caption {
  margin-bottom: var(--space-control-y);
}

/* Button/Primary — Figma node 1:5.
 * Fill = studio810/color/primary, label = studio810/color/on-primary,
 * radius = studio810/radius/control, padding = studio810/space/control-y
 * and control-x, type = studio810/type/*. Mirrors the component's own
 * variable bindings one-for-one. */
.btn--primary {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: none;
  cursor: pointer;
  background: var(--color-primary);
  color: var(--color-on-primary);
  border-radius: var(--radius-control);
  padding: var(--space-control-y) var(--space-control-x);
  font-family: var(--type-family), system-ui, sans-serif;
  font-size: var(--type-size-label);
  font-weight: var(--type-weight-label);
}
${DRIFT ? '\n/* DELIBERATE DRIFT (negative test): raw value, not a published token */\n.drift-injected { background: #ff00aa; }\n' : ''}`;

const componentsUsed = ['studio810/Button/Primary'];

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Studio 810 — DS-001 POC</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
</head>
<body>
  <p class="caption">Studio 810 &bull; DS-001 &bull; Button/Primary, generated from the design tokens</p>
  <section data-figma-node="1:5">
    <button class="btn--primary">Button</button>
  </section>
</body>
</html>
`;

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'styles.css'), css);
writeFileSync(join(OUT, 'index.html'), html);
console.log(`poc-builder: wrote apps/poc/index.html + styles.css (${cssVars.length} css vars, ${componentsUsed.length} component${DRIFT ? ', DRIFT INJECTED' : ''})`);

if (process.env.RUN_ID && !DRIFT) {
  let passed = false;
  let output = '';
  try {
    output = execFileSync('node', [join(ROOT, 'tools/drift-check/index.mjs')], { encoding: 'utf8' });
    passed = true;
  } catch (err) {
    output = String(err.stdout || '') + String(err.stderr || '');
  }
  if (!passed) {
    console.error('poc-builder: local drift-check failed — refusing to write a build report.\n' + output);
    process.exit(1);
  }
  const report = {
    runId: process.env.RUN_ID,
    storiesImplemented: ['S1'],
    filesChanged: ['apps/poc/index.html', 'apps/poc/styles.css'],
    componentsUsed,
    tokensUsed,
    deviations: [],
    driftCheckLocal: { passed: true, output: output.trim() },
  };
  const runDir = join(ROOT, 'pipeline/runs', process.env.RUN_ID);
  mkdirSync(runDir, { recursive: true });
  writeFileSync(join(runDir, '50-build-report.json'), JSON.stringify(report, null, 2) + '\n');
  console.log(`poc-builder: wrote pipeline/runs/${process.env.RUN_ID}/50-build-report.json`);
}
