#!/usr/bin/env node
// poc-builder — Phase 2 deterministic builder.
//
// Generates the Connect POC page (apps/connect/) purely from the synced design
// tokens and the registered Figma component sets: Button/Primary (28:117) and
// Button/Destructive (31:117), each Size(Sm|Md|Lg) x Shape(Pill|Control) x
// State(Default|Hover|Focused|Disabled), mirroring the Figma sheets.
//
// Deterministic on purpose: same tokens in → byte-identical output out,
// regardless of trigger source. Every color and dimension is emitted once as a
// CSS custom property taken verbatim from design/tokens/studio810/tokens.json, so
// the output cannot pass the drift gate unless the tokens themselves did.
//
// Env:
//   RUN_ID       — when set, writes pipeline/runs/$RUN_ID/50-build-report.json
//   DRIFT_INJECT — "1" injects one deliberate raw color so the gate can prove
//                  it blocks drifted builds (Phase 2 negative test)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

const ROOT = new URL('../..', import.meta.url).pathname;
const OUT = join(ROOT, 'apps/connect');
const DRIFT = process.env.DRIFT_INJECT === '1';

const studio810 = JSON.parse(
  readFileSync(join(ROOT, 'design/tokens/studio810/tokens.json'), 'utf8')
).studio810;

const cssVars = [];
const tokensUsed = [];
(function walk(node, path) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('_')) continue;
    const p = path ? `${path}.${key}` : key;
    if (value && typeof value === 'object' && 'value' in value) {
      tokensUsed.push(`studio810.${p}`);
      if (typeof value.figmaName === 'string' && value.figmaName.startsWith('--')) {
        const v = value.type === 'fontFamily' ? `'${value.value}'` : value.value;
        cssVars.push(`  ${value.figmaName}: ${v};`);
      }
    } else if (value && typeof value === 'object') {
      walk(value, p);
    }
  }
})(studio810, '');
cssVars.sort();
tokensUsed.sort();

const css = `/* Generated by tools/poc-builder from design/tokens/studio810/tokens.json.
 * Do not edit by hand — regenerate instead. Every value below resolves to a
 * published Figma variable (docs/drift-gate.md). */

:root {
${cssVars.join('\n')}
}

* { box-sizing: border-box; margin: 0; }

body {
  font-family: var(--font-sans), system-ui, sans-serif;
  background: var(--surface-1);
  color: var(--surface-inverse);
  padding: var(--control-h-md);
}

.eyebrow {
  font-size: var(--text-brand-eyebrow);
  font-weight: var(--weight-medium);
  letter-spacing: var(--text-brand-eyebrow);
  text-transform: uppercase;
}

h1 {
  font-size: var(--text-subheading);
  font-weight: var(--weight-medium);
  margin: var(--space-3) 0 var(--control-px-lg);
}

.sheet {
  background: var(--surface-1);
  border: var(--border-hairline) solid var(--border-subtle);
  border-radius: var(--radius-card);
  padding: var(--control-h-lg);
  margin-bottom: var(--control-px-lg);
}

.sheet h2 {
  font-size: var(--text-label);
  font-weight: var(--weight-medium);
  margin-bottom: var(--control-px-lg);
}

.grid {
  display: grid;
  grid-template-columns: repeat(4, max-content);
  gap: var(--control-h-lg) var(--control-h-lg);
  align-items: center;
}

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-3);
  border: none;
  cursor: pointer;
  font-family: var(--font-sans), system-ui, sans-serif;
  font-weight: var(--weight-medium);
  color: var(--action-fill-text);
}

/* Sizes — heights, paddings, and type straight from control tokens */
.btn--sm { height: var(--control-h-sm); padding: 0 var(--control-px-sm); font-size: var(--text-label); }
.btn--md { height: var(--control-h-md); padding: 0 var(--control-px-md); font-size: var(--text-label); }
.btn--lg { height: var(--control-h-lg); padding: 0 var(--control-px-lg); font-size: var(--text-body); }

/* Shapes */
.btn--pill { border-radius: var(--radius-pill); }
.btn--control { border-radius: var(--radius-control); }

/* Button/Primary */
.btn--primary { background: var(--action-fill); }
.btn--primary:hover, .btn--primary.is-hover { background: var(--action-fill-hover); }

/* Button/Destructive */
.btn--destructive { background: var(--status-danger); }
.btn--destructive:hover, .btn--destructive.is-hover { background: var(--status-danger-fill); }

/* States shared across variants */
.btn:focus-visible, .btn.is-focused {
  outline: var(--border-focus-ring) solid var(--border-focus);
  outline-offset: var(--border-focus-ring);
}
.btn[disabled] { opacity: 0.4; cursor: not-allowed; }
.btn[disabled]:hover { background: var(--action-fill); }
.btn--destructive[disabled]:hover { background: var(--status-danger); }
${DRIFT ? '\n/* DELIBERATE DRIFT (negative test): raw value, not a published token */\n.drift-injected { background: #ff00aa; }\n' : ''}`;

const SIZES = [
  ['md', 'Medium'],
  ['sm', 'Small'],
  ['lg', 'Large'],
];
const SHAPES = [
  ['pill', 'Pill'],
  ['control', 'Control'],
];
const STATES = [
  ['', 'Default'],
  ['is-hover', 'Hover'],
  ['is-focused', 'Focused'],
  ['disabled', 'Disabled'],
];

const componentsUsed = [];

function sheet(variant, title, figmaNode) {
  const rows = [];
  for (const [sizeKey, sizeName] of SIZES) {
    for (const [shapeKey, shapeName] of SHAPES) {
      for (const [stateCls, stateName] of STATES) {
        componentsUsed.push(`studio810/Button/${title}/Size=${sizeName}, Shape=${shapeName}, State=${stateName}`);
        const cls = ['btn', `btn--${variant}`, `btn--${sizeKey}`, `btn--${shapeKey}`, stateCls === 'is-hover' || stateCls === 'is-focused' ? stateCls : '']
          .filter(Boolean)
          .join(' ');
        const disabled = stateCls === 'disabled' ? ' disabled' : '';
        rows.push(`      <button class="${cls}"${disabled} title="${sizeName} / ${shapeName} / ${stateName}">Button</button>`);
      }
    }
  }
  return `  <section class="sheet" data-figma-node="${figmaNode}">
    <h2>Button/${title} — Figma ${figmaNode}</h2>
    <div class="grid">
${rows.join('\n')}
    </div>
  </section>`;
}

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Connect — Studio 810 DS-001 POC</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
</head>
<body>
  <p class="eyebrow">Studio 810 &bull; DS-001 &bull; Pipeline POC</p>
  <h1>Connect &mdash; Button components, generated from the design tokens</h1>
${sheet('primary', 'Primary', '28:117')}
${sheet('destructive', 'Destructive', '31:117')}
</body>
</html>
`;

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'styles.css'), css);
writeFileSync(join(OUT, 'index.html'), html);
console.log(`poc-builder: wrote apps/connect/index.html + styles.css (${cssVars.length} css vars, ${componentsUsed.length} variants${DRIFT ? ', DRIFT INJECTED' : ''})`);

componentsUsed.sort();

if (process.env.RUN_ID && !DRIFT) {
  let passed = false;
  let output = '';
  try {
    output = execFileSync('node', [join(ROOT, 'tools/drift-check/index.mjs')], { encoding: 'utf8' });
    passed = true;
  } catch (err) {
    output = String(err.stdout || '') + String(err.stderr || '');
  }
  if (!passed) {
    console.error('poc-builder: local drift-check failed — refusing to write a build report.\n' + output);
    process.exit(1);
  }
  const report = {
    runId: process.env.RUN_ID,
    storiesImplemented: ['S1'],
    filesChanged: ['apps/connect/index.html', 'apps/connect/styles.css'],
    componentsUsed,
    tokensUsed,
    deviations: [],
    driftCheckLocal: { passed: true, output: output.trim() },
  };
  const runDir = join(ROOT, 'pipeline/runs', process.env.RUN_ID);
  mkdirSync(runDir, { recursive: true });
  writeFileSync(join(runDir, '50-build-report.json'), JSON.stringify(report, null, 2) + '\n');
  console.log(`poc-builder: wrote pipeline/runs/${process.env.RUN_ID}/50-build-report.json`);
}
